name: CI/CD Pipeline

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and run tests
        run: |
          cd CalculatorTests       
          mkdir build
          cd build
          cmake ..
          make
          ./test_calculator

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Deploying to production server"

